const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '../..')
const read = relativePath => fs.readFileSync(path.join(root, relativePath), 'utf8')
const appConfig = JSON.parse(read('app.json'))
const pageJs = read('pages/outfitHistory/outfitHistory.js')
const pageWxml = read('pages/outfitHistory/outfitHistory.wxml')
const pageWxss = read('pages/outfitHistory/outfitHistory.wxss')
const todayJs = read('pages/todayOutfit/todayOutfit.js')
const todayWxml = read('pages/todayOutfit/todayOutfit.wxml')

assert.ok(appConfig.pages.includes('pages/outfitHistory/outfitHistory'))
assert.match(todayJs, /wx\.navigateTo\(\{\s*url:\s*'\/pages\/outfitHistory\/outfitHistory'/)
assert.match(todayWxml, /bindtap="goToOutfitHistory"/)

assert.match(pageWxml, /picker[\s\S]*mode="date"/)
assert.match(pageWxml, /end="\{\{todayDateKey\}\}"/)
assert.match(pageWxml, /class="outfit-list count-\{\{records\.length\}\}"/)
assert.match(pageWxss, /\.outfit-list\.count-1 \.outfit-card[\s\S]*width:\s*88%/)
assert.match(pageWxss, /\.outfit-card[\s\S]*width:\s*calc\(50% - 10rpx\)/)
assert.match(pageWxml, /保存图片/)
assert.match(pageWxml, /今天还没有穿搭记录/)
assert.match(pageWxml, /这一天还没有穿搭记录/)

assert.doesNotMatch(pageWxml, />删除</)
assert.doesNotMatch(pageWxml, /位置\d|slot\s*\{\{|第\d套|今日穿搭\d/)
assert.doesNotMatch(pageWxml, /使用衣物|再次试穿|查看穿搭详情|管理今日穿搭/)
assert.doesNotMatch(pageJs, /wx\.(get|set|remove)StorageSync/)
assert.doesNotMatch(pageJs, /wx\.cloud\.(database|callFunction)/)
assert.match(pageJs, /outfitService\.getOutfitHistory/)
assert.match(pageJs, /previewOutfitImage/)
assert.match(pageJs, /saveOutfitImageToAlbum/)
assert.match(pageJs, /openTryonWithClothingIds/)
assert.match(pageJs, /record\.detailsExpired !== true/)
assert.match(pageJs, /isWithinRecent10Days/)

console.log('outfit-history-page.test.js passed')
