module.exports = {
  ALIBABA_CLOUD_ACCESS_KEY_ID: 'REPLACE_WITH_YOUR_ACCESS_KEY_ID',
  ALIBABA_CLOUD_ACCESS_KEY_SECRET: 'REPLACE_WITH_YOUR_ACCESS_KEY_SECRET',
  WORKSPACE_ID: 'REPLACE_WITH_YOUR_WORKSPACE_ID',
  BAILIAN_REGION_ID: 'cn-beijing',
  BAILIAN_DEFAULT_CATEGORY_ID: 'default',
  BAILIAN_FILE_PARSER: 'DASHSCOPE_DOCMIND',
  BAILIAN_CHUNK_SIZE: 500,
  BAILIAN_OVERLAP_SIZE: 100,
  BAILIAN_POLL_ATTEMPTS: 8,
  BAILIAN_POLL_DELAY_MS: 1200
}
